package com.example.comp1786_l6_firebase;

public class Book {
  private String bookTitle;
  private String bookISBN;
  private float bookPrice;

  private String key; // hold the unique value generated by Firebase

  // Getter for bookTitle
  public String getBookTitle() {
    return bookTitle;
  }

  // Setter for bookTitle
  public void setBookTitle(String bookTitle) {
    this.bookTitle = bookTitle;
  }

  // Getter for bookISBN
  public String getBookISBN() {
    return bookISBN;
  }

  // Setter for bookISBN
  public void setBookISBN(String bookISBN) {
    this.bookISBN = bookISBN;
  }

  // Getter for bookPrice
  public float getBookPrice() {
    return bookPrice;
  }

  // Setter for bookPrice
  public void setBookPrice(float bookPrice) {
    this.bookPrice = bookPrice;
  }

  // Getter for key
  public String getKey() {
    return key;
  }

  // Setter for key
  public void setKey(String key) {
    this.key = key;
  }
}

